[package]
name = "hso-thesis"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Markus Portugall"]
license = "MIT"
description = "Ein Typst-Template für Abschluss- oder Seminararbeiten an der Hochschule Offenburg."
categories = ["thesis", "report", "academic"]
compiler = "0.12.0"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
